#!/usr/bin/env python
# coding: utf-8
"""
Specific/calc_engine.py  --  Calculation engine plugin for GmAte.py

This stub is the default placeholder. Replace it with a concrete implementation,
or copy one of the templates from example/Specific_*/ to Specific/.

Standard interface
------------------
GmAte.py calls:

    score = calc_engine.run(work_dir)

where `work_dir` is the absolute path to an individual's working directory.
That directory contains:

    POSCAR      -- structure file (VASP5 format) generated by GmAte
    temp_gene   -- gene string file written by GmAte

temp_gene format
----------------
One line per ELEM group (NUM_OF_STRINGS lines total).
Each character is an integer index (0, 1, 2 ...) that maps to ELEM in inp_POSCAR.py.

    Example: ELEM = [["Li", "Al"]]
    temp_gene:
        00110011
    → site order: Li Li Al Al Li Li Al Al

    Example: ELEM = [["Li", "Al"], ["Co", "Fe"]]
    temp_gene:
        00110011    ← gene for ELEM1 (Li/Al sites)
        01010101    ← gene for ELEM2 (Co/Fe sites)

Return value
------------
float -- evaluation value (lower = more stable, typically total energy in eV).
"""


def run(work_dir: str) -> float:
    """Execute one structure calculation and return the evaluation value.

    Implement this function for your calculation engine.
    See example/Specific_*/ for concrete templates.
    """
    raise NotImplementedError(
        "Implement run() in Specific/calc_engine.py. "
        "Copy a template from example/Specific_*/ as a starting point."
    )
